//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

 namespace UnderPowerMonitorWindowsService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnderPowerWarning
    {
        public long Id { get; set; }
        public System.DateTime WarningDate { get; set; }
        public int PStationId { get; set; }
        public int IsUnder { get; set; }
        public int TotalDays { get; set; }
        public System.DateTime BeginTime { get; set; }
        public int NetIsUnder { get; set; }
        public int NetTotalDays { get; set; }
        public System.DateTime NetBeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public double kWh { get; set; }
        public double LosskWh { get; set; }
        public double ForecastkWhDay { get; set; }
        public double NetForecastkWhDay { get; set; }
        
        public double TotalkWh { get; set; }
        public double TotalLosskWh { get; set; }
        public double TotalForecastkWh { get; set; }
        public double TotalNetForecastkWh { get; set; }
        
        public double TotalFaultLoss { get; set; }
        public double TotalNotFaultLoss { get; set; }
        public int ContractDateId { get; set; }
        public int ContractDays { get; set; }      
        public string Remark { get; set; }
        public string CreateUserId { get; set; }
        public string CreateDate { get; set; }
        public string UpdateUserId { get; set; }
        public string UpdateDate { get; set; }
        public string DelFlg { get; set; }
        public int UpdateVersion { get; set; }
    }
}
